AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Setting up IAM users for Serverless CatDetector workshop. That will be used
  for creating Serverless application on top of Amazon Services, including
  Amazon Rekognition and others.

Parameters:

  PASSWORD:
    Description: >
      Start password for a participant.
    Type: String
    NoEcho: true

Resources:

  User001:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user001"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User002:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user002"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User003:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user003"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User004:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user004"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User005:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user005"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User006:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user006"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User007:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user007"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User008:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user008"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User009:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user009"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User010:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user010"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User011:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user011"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User012:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user012"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User013:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user013"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User014:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user014"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User015:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user015"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User016:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user016"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User017:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user017"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User018:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user018"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User019:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user019"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User020:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user020"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User021:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user021"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User022:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user022"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User023:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user023"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User024:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user024"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User025:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user025"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User026:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user026"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User027:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user027"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User028:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user028"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User029:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user029"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User030:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user030"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User031:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user031"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  User032:
    Type: AWS::IAM::User
    Properties:
      UserName: "serverless-cat-detector-user032"
      LoginProfile:
        Password: !Ref "PASSWORD"
        PasswordResetRequired: true

  ParticipantPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - User001
      - User002
      - User003
      - User004
      - User005
      - User006
      - User007
      - User008
      - User009
      - User010
      - User011
      - User012
      - User013
      - User014
      - User015
      - User016
      - User017
      - User018
      - User019
      - User020
      - User021
      - User022
      - User023
      - User024
      - User025
      - User026
      - User027
      - User028
      - User029
      - User030
      - User031
      - User032
    Properties:
      Users:
        - !Ref "User001"
        - !Ref "User002"
        - !Ref "User003"
        - !Ref "User004"
        - !Ref "User005"
        - !Ref "User006"
        - !Ref "User007"
        - !Ref "User008"
        - !Ref "User009"
        - !Ref "User010"
        - !Ref "User011"
        - !Ref "User012"
        - !Ref "User013"
        - !Ref "User014"
        - !Ref "User015"
        - !Ref "User016"
        - !Ref "User017"
        - !Ref "User018"
        - !Ref "User019"
        - !Ref "User020"
        - !Ref "User021"
        - !Ref "User022"
        - !Ref "User023"
        - !Ref "User024"
        - !Ref "User025"
        - !Ref "User026"
        - !Ref "User027"
        - !Ref "User028"
        - !Ref "User029"
        - !Ref "User030"
        - !Ref "User031"
        - !Ref "User032"
      PolicyName: "serverless-cat-detector-cloudyna2017-participant-policy"
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:*
              - rekognition:*
              - dynamodb:*
              - lambda:*
              - xray:*
              - cloudwatch:*
              - iam:*
              - apigateway:*
              - execute-api:*

              - sns:*
              - tag:*
              - kms:ListAliases
              - cloudformation:DescribeStackResources
            Resource: "*"