service: serverless-cat-detector

provider:
  name: aws
  region: eu-west-1
  profile: appliscale-dev
  runtime: nodejs6.10
  tracing: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - rekognition:*
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: Allow
      Action:
        - xray:*
      Resource: "*"

functions:
  uploadcatpicture:
    handler: src/upload.saveToS3
    events:
      - http:
          path: upload
          method: post
          cors: true
  getresults:
    handler: src/results.getClassification
    events:
     - http:
         path: results
         method: get
  catrekognition:
    handler: src/handler.imgClassification

resources:
  Resources:
    S3BucketServerlessDashCatDashDetectorDashImgDashRepo:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: serverless-cat-detector-img-repo
        NotificationConfiguration:
          LambdaConfigurations:
            - Event:  "s3:ObjectCreated:*"
              Function:
                "Fn::GetAtt": [CatrekognitionLambdaFunction, Arn]
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: ["GET", "PUT"]
              AllowedOrigins: ["*"]
    CatrekognitionLambdaPermissionS3BucketMyBucketDevS3:
      DependsOn:
        - CatrekognitionLambdaFunction
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt": [ CatrekognitionLambdaFunction, Arn ]
        Action: "lambda:InvokeFunction"
        Principal: "s3.amazonaws.com"
        SourceArn: "arn:aws:s3:::serverless-cat-detector-img-repo"
    CatStatusDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: 'name'
            AttributeType: S
        KeySchema:
          -
            AttributeName: 'name'
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: 'ServerlessCatDetectorStatus'

plugins:
  - serverless-s3-remover
  - serverless-plugin-tracing

custom:
  remover:
    buckets:
      - serverless-cat-detector-img-repo